In [3]:
'''
Task 1 — Student Marks Array
-------------------------------------
Goal:
====
Create a NumPy array for student marks and perform basic operations.
Topics Covered : Array, Array Slicing ,Mathematical Operations
Task
======
1. Create an array of marks:[45, 67, 89, 90, 76]
2. Print:
First 3 marks
Last 2 marks
Add 5 bonus marks to all students
Expected Result
==============
First 3 Marks: [45 67 89]
Last 2 Marks: [90 76]
Updated Marks:'''
import numpy as np
marks=[45, 67, 89, 90, 76]
cmarks=np.array(marks)
# 1st 3 marks
print(cmarks[1:4])

#last 2 marks
print(cmarks[3:5])

#addbonus 5 to all student marks
print(cmarks+5)

[67 89 90]
[90 76]
[50 72 94 95 81]


In [14]:
'''
Task 2 — Create Special Arrays
=========================
Goal :Learn how to create arrays filled with zeros, ones, and identity matrix.
Topics Covered: Zeros and Ones, Identity Matrix
Task
1. Create:
3×3 zero matrix
2×4 ones matrix
4×4 identity matrix
Expected Result:
==============
Zeros Matrix:
[[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]]
Ones Matrix:
[[1. 1. 1. 1.]
[1. 1. 1. 1.]]
Identity Matrix:
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]

[0. 0. 0. 1.]]  '''

import numpy as np

# 1. 3x3 Zero Matrix
zeros_matrix = np.zeros((3, 3))
print("Zeros Matrix:")
print(zeros_matrix)

# 2. 2x4 Ones Matrix
ones_matrix = np.ones((2, 4))
print("\nOnes Matrix:")
print(ones_matrix)

# 3. 4x4 Identity Matrix
identity_matrix = np.eye(4)
print("\nIdentity Matrix:")
print(identity_matrix)


Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
'''
Task 3 — Random Number Generator
==============================
Goal: Generate random decimal and integer numbers.
Topics Covered: Random Numbers,Random Integer
Task
====
1. Generate:
5 random decimal numbers
10 random integers between 1 and 50
Expected Result:
(Output changes every time)
Random Decimal Numbers: [0.45 0.91 0.12 0.67 0.88]
Random Integers: [12 45 7 33 18 29 50 4 11 26]
'''

import numpy as np


decimals = np.random.rand(5)
print("Random Decimal Numbers:", decimals)
# start , end value , total size of array is 10
integers = np.random.randint(1, 51, size=10)
print("Random Integers:", integers)

Random Decimal Numbers: [0.37946799 0.27072605 0.026125   0.82203452 0.4252409 ]
Random Integers: [ 6 43 26 44  1 41 11 21 34 13]


In [17]:
'''

Task 4 — Reshape Employee Data
============================
Goal: Convert 1D array into 2D array.
Topics Covered: Reshape
Task
====
1. Create array: [1,2,3,4,5,6]
2. Convert into: 2 rows and 3 columns
Expected Result:
[[1 2 3]
[4 5 6]]

'''
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6])


reshape= arr.reshape(2, 3)

print(reshape)


[[1 2 3]
 [4 5 6]]


In [18]:
'''
Task 5 — Matrix Operations
=======================
Goal: Perform matrix multiplication and transpose.
Topics Covered: Matrix Multiplication, Transpose
Task
=====
Given:A = [[1,2],[3,4]], B = [[5,6],[7,8]]
1. Multiply A and B
2. Find transpose of A
Expected Result: Matrix Multiplication:[[19 22] [43 50]]
Transpose of A:[[1 3] [2 4]]
'''
import numpy as np

a = np.array([[1, 2], 
              [3, 4]])

print(np.transpose(a))
print(a.T)


[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [29]:
a = np.array([[2, 4, 6] , [23 , 23 , 23]])
b = np.array([[1, 3, 5] , [45 , 45 , 56]])
result = a * b   
print(result)

[[   2   12   30]
 [1035 1035 1288]]


In [33]:
'''
Task 6 — Analyze Student Scores
===========================
Goal: Find statistical values from marks.
Topics Covered: Mean, Median, Standard Deviation
Task
====
Marks:[78, 85, 90, 62, 88]
Find: Mean, Median, Standard deviation
Expected Result: Mean: 80.6,Median: 85.0,Standard Deviation: 10.1'''

arr = np.array([78, 85, 90, 62, 88])
stddev = np.std(arr)
print(stddev)  
mean=np.mean(arr)
print(mean)
median=np.median(arr)
print(median)


10.150862032359617
80.6
85.0


In [36]:
'''
Task 7 — Sorting and Unique Elements
================================
Goal: Learn sorting and removing duplicates.
Topics Covered: Sorting, Unique Elements
Task
====
Array:[5,2,8,2,9,1,5]
1. Sort the array
2. Find unique values
'''
arr=[23,22,22,22,2]
uni=np.unique(arr)
print(uni)
so=np.sort(arr)
print(so)

[ 2 22 23]
[ 2 22 22 22 23]


In [5]:
b=[1,3,5,2]
b=np.array(b)
print(arr+b )

[11 23 35 42]


In [4]:
'''
Task 8 — Combine and Generate Values
=================================
Goal:Combine arrays and generate evenly spaced numbers.
Topics Covered: Concatenate, Linspace
Task
=====
1. Concatenate: [1,2,3] and [4,5,6]
2. Generate 5 values between 0 and 10 using linspace
Expected Result: Concatenated Array: [1 2 3 4 5 6],Linspace Values: [ 0. 2.5 5. 7.5 10. ]
 linspace : start    , stop , num

'''

arr = np.array([10, 20, 30, 40])
b = [1, 3, 5, 2]
b = np.array(b)
lp=np.linspace(0,10,5)
print(arr + b) 
print(lp)

[11 23 35 42]
[ 0.   2.5  5.   7.5 10. ]


In [47]:
'''
Task 9 — Find Maximum, Minimum and Conditions
=========================================

Goal: Find positions of max/min values and apply conditions.
Topics Covered: Argmax and Argmin, Where Condition
Task
=====
Array: [23, 45, 12, 67, 34]
1. Find: Index of maximum value,Index of minimum value
2. Find numbers greater than 30 using where condition
Expected Result: Argmax Index: 3 , Argmin Index: 2,Values Greater Than 30: [45 67 34]

'''



arr = np.array([23, 45, 12, 67, 34])


max_idx = np.argmax(arr)
min_idx = np.argmin(arr)


ig30 = np.where(arr > 30)
vg30 = arr[indices_greater_30]


print(f"Argmax Index: {max_idx}")
print(f"Argmin Index: {min_idx}")
print(f"Values Greater Than 30: {vg30}")

Argmax Index: 3
Argmin Index: 2
Values Greater Than 30: [45 67 34]


In [64]:
'''

Task 10 — Sales Analysis Project
===========================
Goal: Perform cumulative sum, correlation coefficient, and save/load Numpy array.
Topics Covered: Cumulative Sum, Correlation Coefficient, Save and Load Numpy Array
Task
====
Part 1 — Cumulative Sum
Sales:[100, 200, 150, 300]
Find cumulative sum.
--------------------------------------
Part 2 — Correlation Coefficient
Study hours: [1,2,3,4,5]
Marks: [20,40,50,70,90
Find correlation coefficient.
----------------------------------------
Part 3 — Save and Load
1. Save: [10,20,30,40] into a file.
2. Load it again.
Expected Result
=============
Cumulative Sum: [100 300 450 750]
Correlation Coefficient: 0.98 (approximately)
Loaded Array:[10 20 30 40]
===================================================
'''
#part 1
sales  = np.array([100 , 200 , 150 , 300])
result = np.cumsum(arr)

print(result)

#part 2

study_hours= np.array([1,2,3,4,5])
marks=np.array([20,40,50,70,90])
ccoef=np.corrcoef(study_hours,marks)
print(ccoef)

#part 3
save_arr = np.array([10, 20, 30, 40])
np.save("save.npy", save_arr)  

loaded_array = np.load("save.npy")
print("Loaded Array:", loaded_array)

[ 1  3  6 10 15]
[[1.         0.99484975]
 [0.99484975 1.        ]]
Loaded Array: [10 20 30 40]
